# This is a basic workflow that is manually triggered

name: Homebrew Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  release:
    types:
      - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy Homebrew
    runs-on: ubuntu-20.04
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.REPOSITORY_KEY }}

    steps:
      - uses: actions/checkout@v1
      - name: Setup Dart
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: stable

      - name: Install dependencies
        run: dart pub get

      - name: Build Version Number
        run: dart  run build_runner build --delete-conflicting-outputs

      - name: Deploy to Homebrew
        run: dart run grinder pkg-homebrew-update