# This is a basic workflow that is manually triggered

name: Homebrew Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy Homebrew
    runs-on: ubuntu-latest
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.TOKEN_PUBLISH }}
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.17.5

      - name: Install dependencies
        run: dart pub get

      - name: Build Version Number
        run: dart run build_runner build --delete-conflicting-outputs
      
      - name: Deploy Github
        run: dart run grinder pkg-github-all

      - name: Deploy to Pub
        run: dart run grinder pkg-pub-deploy

      - name: Deploy to Homebrew
        run: dart run grinder pkg-homebrew-update
