name: Dart Release Creator
on:
  push:
    branches:
      - 'stable'

jobs:
  create-tag:
    runs-on: ubuntu-20.04
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.REPOSITORY_KEY }}
    steps:
    - uses: actions/checkout@v1
    - name: Get pubspec version
      run: |
        echo "PUBSPEC_VERSION=$(cat pubspec.yaml | grep ^version: | tr -d 'version: ')" >> $GITHUB_ENV
    - name: Create tag
      uses: rickstaa/action-create-tag@v1
      with:
        github_token: ${{ secrets.REPOSITORY_KEY }} 
        tag: v${{ env.PUBSPEC_VERSION }}
        message: | 
          See the [full changelog](https://github.com/Flutterando/slidy/blob/master/CHANGELOG.md#322) for changes in earlier releases.

    - uses: dart-lang/setup-dart@v1.3
      with:
        sdk: 2.17.5
    - name: Install dependencies
      run: dart pub get

    - name: Build Version Number
      run: dart run build_runner build --delete-conflicting-outputs
    
    - name: Deploy Github
      run: dart run grinder pkg-github-all

    - name: Deploy to Pub
      run: dart run grinder pkg-pub-deploy

    